Repository Workday-Pod-4/CollabU, pull requests merged in 2022-07, with the labels that each got.

#34 Login page
  capstone-project/ui/src/components/App/App.jsx
  capstone-project/ui/src/components/LoginPage/LoginForm.jsx
  capstone-project/ui/src/components/LoginPage/LoginPage.css
  capstone-project/ui/src/components/LoginPage/LoginPage.jsx
Labels: enhancement, frontend

#35 Registration page
  capstone-project/ui/src/components/App/App.jsx
  capstone-project/ui/src/components/RegistrationPage/RegistrationForm.jsx
  capstone-project/ui/src/components/RegistrationPage/RegistrationPage.css
  capstone-project/ui/src/components/RegistrationPage/RegistrationPage.jsx
Labels: enhancement, frontend

#36 Landingpage
  capstone-project/ui/src/components/About/About.css
  capstone-project/ui/src/components/About/About.jsx
  capstone-project/ui/src/components/App/App.jsx
  capstone-project/ui/src/components/ContactCard/ContactCard.css
  capstone-project/ui/src/components/ContactCard/ContactCard.jsx
  capstone-project/ui/src/components/ContactForm/ContactForm.css
  capstone-project/ui/src/components/ContactForm/ContactForm.jsx
  capstone-project/ui/src/components/ContactUs/ContactUs.css
  capstone-project/ui/src/components/ContactUs/ContactUs.jsx
  capstone-project/ui/src/components/Footer/Footer.css
  capstone-project/ui/src/components/Footer/Footer.jsx
  capstone-project/ui/src/components/Hero/Hero.css
  capstone-project/ui/src/components/Hero/Hero.jsx
  capstone-project/ui/src/components/LandingPage/LandingPage.css
  capstone-project/ui/src/components/LandingPage/LandingPage.jsx
Labels: frontend

#38 Started implementing UpdateForm component
  capstone-project/ui/src/components/ProfilePage/ProfilePage.css
  capstone-project/ui/src/components/ProfilePage/UpdateForm.css
  capstone-project/ui/src/components/ProfilePage/UpdateForm.jsx
Labels: enhancement, frontend

#40 Additional info
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
  capstone-project/ui/src/components/ProfilePage/AdditionalInfo.css
  capstone-project/ui/src/components/ProfilePage/AdditionalInfo.jsx
  capstone-project/ui/src/components/ProfilePage/ProfilePage.jsx
Labels: enhancement, frontend

#44 Revert "Preference modal"
  capstone-project/ui/src/components/App/App.jsx
  capstone-project/ui/src/components/NavLinks/NavLinks.css
  capstone-project/ui/src/components/NavLinks/NavLinks.jsx
  capstone-project/ui/src/components/PreferenceModal/PreferenceModal.css
  capstone-project/ui/src/components/PreferenceModal/PreferenceModal.jsx
  capstone-project/ui/src/components/ProfilePage/ProfilePage.css
  capstone-project/ui/src/components/ProfilePage/ProfilePage.jsx
  capstone-project/ui/src/contexts/auth.jsx
Labels: bug, frontend

#45 Merging Restyled preference modal
  capstone-project/ui/src/components/PreferenceModal/PreferenceModal.css
  capstone-project/ui/src/components/PreferenceModal/PreferenceModal.jsx
Labels: frontend

#48 Preference modal duplicate
  capstone-project/ui/src/components/NavLinks/NavLinks.css
  capstone-project/ui/src/components/NavLinks/NavLinks.jsx
  capstone-project/ui/src/components/PreferenceModal/PreferenceModal.css
  capstone-project/ui/src/components/PreferenceModal/PreferenceModal.jsx
  capstone-project/ui/src/components/ProfilePage/ProfilePage.jsx
  capstone-project/ui/src/contexts/auth.jsx
Labels: frontend

#49 Chat box
  capstone-project/ui/src/components/ChatRoom/ChatRoom.css
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
  capstone-project/ui/src/contexts/auth.jsx
Labels: enhancement, frontend

#50 settings modal
  capstone-project/ui/src/components/PreferenceModal/PreferenceModal.css
  capstone-project/ui/src/components/PreferenceModal/PreferenceModal.jsx
  capstone-project/ui/src/components/ProfilePage/ProfilePage.jsx
  capstone-project/ui/src/components/SettingsModal/SettingsModal.css
  capstone-project/ui/src/components/SettingsModal/SettingsModal.jsx
  capstone-project/ui/src/contexts/auth.jsx
Labels: frontend

#53 Final room
  capstone-project/api/app.js
  capstone-project/api/capstone-schema.sql
  capstone-project/api/config.js
  capstone-project/api/db.js
  capstone-project/api/models/user.js
  capstone-project/api/package-lock.json
  capstone-project/api/package.json
  capstone-project/api/routes/auth.js
  capstone-project/api/server.js
  capstone-project/api/utils/errors.js
  capstone-project/ui/index.html
  capstone-project/ui/package-lock.json
  capstone-project/ui/package.json
  capstone-project/ui/src/components/About/About.jsx
  capstone-project/ui/src/components/App/App.jsx
  capstone-project/ui/src/components/ChatRoom/ChatRoom.css
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
  capstone-project/ui/src/components/ContactCard/ContactCard.jsx
  capstone-project/ui/src/components/ContactForm/ContactForm.jsx
  capstone-project/ui/src/components/ContactUs/ContactUs.jsx
  capstone-project/ui/src/components/Footer/Footer.jsx
  capstone-project/ui/src/components/Hero/Hero.jsx
  capstone-project/ui/src/components/LandingPage/LandingPage.jsx
  capstone-project/ui/src/components/Loading/Loading.css
  capstone-project/ui/src/components/Loading/Loading.jsx
  capstone-project/ui/src/components/LoginPage/LoginForm.jsx
  capstone-project/ui/src/components/LoginPage/LoginPage.jsx
  capstone-project/ui/src/components/NavLinks/NavLinks.jsx
  capstone-project/ui/src/components/Navbar/Navbar.jsx
  capstone-project/ui/src/components/PreferenceModal/PreferenceModal.jsx
  capstone-project/ui/src/components/ProfilePage/AdditionalInfo.jsx
  capstone-project/ui/src/components/ProfilePage/PreferenceModal.css
  capstone-project/ui/src/components/ProfilePage/ProfilePage.jsx
  capstone-project/ui/src/components/ProfilePage/UpdateForm.jsx
  capstone-project/ui/src/contexts/auth.jsx
  capstone-project/ui/src/main.jsx
Labels: frontend, backend

#54 Login page is fully responsive
  capstone-project/ui/src/components/LoginPage/LoginPage.css
Labels: enhancement, frontend

#55 Registration Page is Responsive
  capstone-project/ui/src/components/RegistrationPage/RegistrationPage.css
Labels: enhancement, frontend

#59 added audio mute functionality, polished user matching algorithm, add…
  capstone-project/api/models/user.js
  capstone-project/api/server.js
  capstone-project/ui/src/components/ChatRoom/ChatRoom.css
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
  capstone-project/ui/src/components/Loading/Loading.css
  capstone-project/ui/src/components/Loading/Loading.jsx
Labels: frontend, backend

#60 Contact form
  capstone-project/ui/package-lock.json
  capstone-project/ui/package.json
  capstone-project/ui/src/components/ContactForm/ContactForm.css
  capstone-project/ui/src/components/ContactForm/ContactForm.jsx
  capstone-project/ui/src/components/Hero/Hero.jsx
  capstone-project/ui/src/components/LandingPage/LandingPage.css
Labels: frontend

#61 fixed a bug with chatroom ui
  capstone-project/api/server.js
  capstone-project/ui/src/components/ChatRoom/ChatRoom.css
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
Labels: bug
