Repository Workday-Pod-4/CollabU, pull requests merged in 2022-08, with the labels that each got.

#69 Changed the NavBar to interact with the ChatRoom
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
  capstone-project/ui/src/components/NavLinks/NavLinks.jsx
  capstone-project/ui/src/components/Navbar/Navbar.jsx
  capstone-project/ui/src/contexts/auth.jsx
Labels: enhancement, frontend

#70 User history
  capstone-project/api/app.js
  capstone-project/api/server.js
  capstone-project/ui/src/components/AccessForbidden/AccessForbidden.css
  capstone-project/ui/src/components/AccessForbidden/AccessForbidden.jsx
  capstone-project/ui/src/components/App/App.jsx
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
  capstone-project/ui/src/components/Loading/Loading.jsx
  capstone-project/ui/src/components/NotFound/NotFound.css
  capstone-project/ui/src/components/NotFound/NotFound.jsx
  capstone-project/ui/src/components/ProfilePage/Loading.css
  capstone-project/ui/src/components/ProfilePage/ProfilePage.jsx
Labels: frontend, backend

#74 Responsiveness
  capstone-project/ui/src/components/LoginPage/LoginPage.css
  capstone-project/ui/src/components/NavLinks/NavLinks.css
  capstone-project/ui/src/components/ProfilePage/AdditionalInfo.css
  capstone-project/ui/src/components/ProfilePage/AdditionalInfo.jsx
  capstone-project/ui/src/components/ProfilePage/Loading.css
  capstone-project/ui/src/components/ProfilePage/PreferenceModal.css
  capstone-project/ui/src/components/ProfilePage/ProfilePage.css
  capstone-project/ui/src/components/ProfilePage/ProfilePage.jsx
  capstone-project/ui/src/components/ProfilePage/UpdateForm.css
  capstone-project/ui/src/components/RegistrationPage/RegistrationPage.css
Labels: enhancement, frontend

#80 Made a pop-up for the exit room
  capstone-project/ui/src/components/ChatRoom/ChatRoom.css
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
  capstone-project/ui/src/components/NavLinks/NavLinks.jsx
  capstone-project/ui/src/contexts/auth.jsx
Labels: frontend

#81 New Update Form
  capstone-project/ui/src/components/ProfilePage/ProfilePage.css
  capstone-project/ui/src/components/ProfilePage/ProfilePage.jsx
  capstone-project/ui/src/components/ProfilePage/UpdateForm.css
  capstone-project/ui/src/components/ProfilePage/UpdateForm.jsx
Labels: enhancement, frontend

#82 Turn off/on video feed
  capstone-project/api/capstone-schema.sql
  capstone-project/api/models/user.js
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
  capstone-project/ui/src/components/ProfilePage/AdditionalInfo.jsx
  capstone-project/ui/src/components/ProfilePage/ProfilePage.jsx
  capstone-project/ui/src/contexts/auth.jsx
Labels: frontend, backend

#83 Added Mute Audio Functionality
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
Labels: frontend, backend

#86 fixed major bug in profile page
  capstone-project/ui/src/components/ProfilePage/ProfilePage.jsx
Labels: frontend

#88 Updated Dropdowns format
  capstone-project/ui/src/components/ProfilePage/ProfilePage.jsx
  capstone-project/ui/src/components/ProfilePage/UpdateForm.jsx
  capstone-project/ui/src/contexts/auth.jsx
Labels: enhancement, frontend

#89 Chat room buttons
  capstone-project/ui/src/assets/mute-svgrepo-com.svg
  capstone-project/ui/src/assets/muted-svgrepo-com.svg
  capstone-project/ui/src/components/ChatRoom/ChatRoom.css
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
Labels: enhancement, frontend

#90 Completed the Disconnect Room Functionality, Fixed 403/404 Rendering Bug, and Completed Chatbox For Room
  capstone-project/api/app.js
  capstone-project/api/server.js
  capstone-project/ui/src/components/App/App.jsx
  capstone-project/ui/src/components/ChatRoom/ChatRoom.css
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
  capstone-project/ui/src/components/Loading/Loading.css
  capstone-project/ui/src/components/Loading/Loading.jsx
  capstone-project/ui/src/components/NavLinks/NavLinks.jsx
  capstone-project/ui/src/components/ProfilePage/ProfilePage.jsx
  capstone-project/ui/src/contexts/auth.jsx
Labels: frontend, backend

#91 Made some minor bug fixes
  capstone-project/api/server.js
  capstone-project/ui/src/components/ChatRoom/ChatRoom.css
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
Labels: bug, frontend, backend

#92 more minor fixes
  capstone-project/ui/src/components/ChatRoom/ChatRoom.css
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
  capstone-project/ui/src/components/ProfilePage/ProfilePage.jsx
Labels: bug, frontend, backend

#93 Updating forms
  capstone-project/ui/src/components/ProfilePage/ProfilePage.jsx
  capstone-project/ui/src/components/ProfilePage/UpdateForm.jsx
  capstone-project/ui/src/contexts/auth.jsx
Labels: enhancement, frontend

#95 Updated dropdown information for additionalInfo modal
  capstone-project/ui/src/components/ProfilePage/AdditionalInfo.jsx
Labels: frontend

#97 Finished Chatbox
  capstone-project/api/app.js
  capstone-project/api/package-lock.json
  capstone-project/api/package.json
  capstone-project/api/server.js
  capstone-project/ui/package-lock.json
  capstone-project/ui/src/components/ChatRoom/ChatRoom.css
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
  capstone-project/ui/src/components/ContactForm/ContactForm.css
  capstone-project/ui/src/components/ProfilePage/ProfilePage.css
  capstone-project/ui/src/components/ReportIssueModal/ReportIssueModal.css
  capstone-project/ui/src/contexts/auth.jsx
Labels: frontend

#99 Few thingies
  capstone-project/ui/src/components/About/About.css
  capstone-project/ui/src/components/About/About.jsx
  capstone-project/ui/src/components/App/App.css
  capstone-project/ui/src/components/ChatRoom/ChatRoom.css
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
  capstone-project/ui/src/components/Hero/Hero.css
  capstone-project/ui/src/components/Hero/Hero.jsx
  capstone-project/ui/src/components/LandingPage/LandingPage.css
  capstone-project/ui/src/components/LoginPage/LoginPage.css
  capstone-project/ui/src/components/MatchModal/MatchModal.css
  capstone-project/ui/src/components/NavLinks/NavLinks.css
  capstone-project/ui/src/components/Navbar/Navbar.css
  capstone-project/ui/src/components/Navbar/Navbar.jsx
  capstone-project/ui/src/components/NotFound/NotFound.css
  capstone-project/ui/src/components/NotFound/NotFound.jsx
  capstone-project/ui/src/components/ProfilePage/Loading.css
  capstone-project/ui/src/components/ProfilePage/PreferenceModal.css
  capstone-project/ui/src/components/ProfilePage/ProfilePage.css
  capstone-project/ui/src/components/RegistrationPage/RegistrationPage.css
  capstone-project/ui/src/components/ReportIssueModal/ReportIssueModal.css
  capstone-project/ui/src/components/SettingsModal/SettingsModal.css
Labels: frontend

#100 added tips to room
  capstone-project/ui/src/components/ChatRoom/ChatRoom.css
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
Labels: frontend

#101 Implemented a disconnection modal
  capstone-project/ui/src/components/ChatRoom/ChatRoom.css
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
  capstone-project/ui/src/components/ProfilePage/ProfilePage.css
  capstone-project/ui/src/contexts/auth.jsx
Labels: frontend

#102 change styling and position of mute button
  capstone-project/ui/src/components/ChatRoom/ChatRoom.css
  capstone-project/ui/src/components/ChatRoom/ChatRoom.jsx
Labels: frontend

#104 Styling fixes
  capstone-project/ui/index.html
  capstone-project/ui/src/assets/CollabU-header.png
  capstone-project/ui/src/components/ChatRoom/ChatRoom.css
  capstone-project/ui/src/components/MatchModal/MatchModal.css
  capstone-project/ui/src/components/MatchModal/MatchModal.jsx
  capstone-project/ui/src/components/NavLinks/NavLinks.css
  capstone-project/ui/src/components/ProfilePage/ProfilePage.jsx
Labels: frontend
